### ISSUE TITLE
Feature Request on dynamicHoses

### ISSUE THREAD

**Issue by deutzfahraustria** [stijnwop/manualAttaching#6]
Goedenavond,
As written on VD Discord, I'd like to make a request on adding a objectChange tag for dynamic hoses.
For example, rotationActive/inactive, translationActive/inactive and visibilityActive/Inactive.
The idea would be, if hydraulic hose 1 gets attached to the tractor, then open flap from coupling 1, both from tractor and attachment. Like this for example: http://www.k-m-hydrauliksysteme.de/gif/oeldruckmaster-festmontage.jpg https://thumbs.ebaystatic.com/d/l225/m/mBLnb1K1EECN6OaXGZCcB3A.jpg
This could work on hydraulic, electric and air couplings.
Best regards,
DeutzFahrAustria

**Comment by stijnwop** [comment]
Morning, 
Basically just the possibility to set an used position and unused position?
One thing tho, when implementing the rotation/translation the movement will not have transition like animation has.. not sure whats preferred in this case?

**Comment by deutzfahraustria** [comment]
Yes, one when hose is not attached and one when hose is attached. I don't think an animation is needed, just switch to opened position when the hose gets attached and closed position when no hose it attached
