### ISSUE TITLE
Errors in log due to missing tags in Russian translation

### ISSUE THREAD

**Issue by fdanapfel** [stijnwop/manualAttaching#9]
When using the latest version of the mod from here I get the following errors in the log.txt:
`Error: /Users/user/Library/Application Support/FarmingSimulator2017/mods/FS17_manualAttaching/modDesc.xml. Этот мод вынуждает присоединять/отсоединять оборудование и прицепы только вручную.
Мы надеемся вам понравится этот мод.</ru>
    </description>

    <iconFilename>icon.png</iconFilename>
    <multiplayer supported="true"/>

    <extraSourceFiles>
        <sourceFile filename="src/ManualAttachingRegistrationHelper.lua"/>
    </extraSourceFiles>

    <l10n>
        <text name="MANUAL_ATTACHING_ATTACH">
            <en>Attach %s</en>
            <de>%s ankuppeln</de>
            <nl>%s aankoppelen</nl>
            <pl>Zaczep %s</pl>
            <ru>Присоединить %s</ru
        </text>
        <text name="MANUAL_ATTACHING_DETACH">
            <en>Detach %s</en>
            <de>%s abkuppeln</de>
            <nl>%s afkoppelen</nl>
            <pl>Odczep %s</pl>
            <ru>Отсоединить %s</ru>
        </text>
        <text name="MANUAL_ATTACHING_ATTACHPTO">
            <en>Attach PTO of %s</en>
            <de>Zapfwelle von %s ankuppeln</de>
            <nl>PTO van %s aankoppelen</nl>
            <pl>Podłącz WOM od %s</pl>
            <ru>Присоединить вал %s</ru>
        </text>
        <text name="MANUAL_ATTACHING_DETACHPTO">
            <en>Detach PTO of %s</en>
            <de>Zapfwelle von %s abkuppeln</de>
            <nl>PTO van %s afkoppelen</nl>
            <pl>Odłącz WOM od %s</pl>
            <ru>Отсоединить вал %s</ru>
        </text>
        <text name="MANUAL_ATTACHING_ATTACHDYNAMICHOSES">
            <en>Hold to attach hoses of %s</en>
            <de>Schläuche von %s ankuppeln</de>
            <nl>Houd ingedrukt om de slangen van %s aan te koppelen</nl>
            <pl>Przytrzymaj, aby podłączyć węże od %s</pl>
            <ru>Нажмите и удерживайте, чтобы присоединить шланги %s</ru>
        </Load mod: FS17_manualAttaching
Error: Missing descVersion attribute in mod FS17_manualAttaching`

This is due to the CDATA tag not being closed correctly, theres the "]]>" missing at the end. There is also a missing ">" behind "ru" in the l10n section for MANUAL_ATTACHING_ATTACH.

**Comment by stijnwop** [comment]
Fixed.

**Comment by fdanapfel** [comment]
The fix is missing the ">" in the following line:
`        <ru>Присоединить %s</ru`

**Comment by stijnwop** [comment]
Should have been fixed. :)
